apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: java-example
spec:
  image: public.ecr.aws/emr-on-eks/flink/emr-7.0.0-flink:latest
  imagePullPolicy: Always
  flinkVersion: v1_18
  executionRoleArn: arn:aws:iam::{ ACCOUNT ID }:role/emr-eks-job-execution-FLINK-ROLE
  emrReleaseLabel: "emr-7.0.0-flink-latest"
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
    taskmanager.memory.jvm-metaspace.size: "512m"
  jobManager:
    storageDir: s3://{ BUCKET NAME }/jobmanager/
    resource:
      memory: "4096m"
      cpu: 2
  taskManager:
    resource:
      memory: "4096m"
      cpu: 2
  job:
    jarURI: s3://{ BUCKET NAME }/scripts/emr-on-eks-workshop-flink-java-0.1.jar
    args: ["{ KINESIS STREAM NAME }", "us-east-1", "{ BUCKET NAME }"]
    parallelism: 2
    upgradeMode: stateless
  monitoringConfiguration:
    image: public.ecr.aws/emr-on-eks/fluentd/emr-7.0.0:latest
    cloudWatchMonitoringConfiguration:
       logGroupName: /aws/emr-eks/flink